// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl0HRAn9XVHC1X1b-Ppl8w2Lmo3Urxos8',
    appId: '1:932311312417:web:f1bde862fb18e4eb759b60',
    messagingSenderId: '932311312417',
    projectId: 'iot-fa-c7ba2',
    authDomain: 'iot-fa-c7ba2.firebaseapp.com',
    storageBucket: 'iot-fa-c7ba2.firebasestorage.app',
    measurementId: 'G-6BN7WPK7HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeEsYceWJhlbX4oDdaI6a76ol7BxsffRE',
    appId: '1:932311312417:android:7db01217bc5ca3dd759b60',
    messagingSenderId: '932311312417',
    projectId: 'iot-fa-c7ba2',
    storageBucket: 'iot-fa-c7ba2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYMDuyrv7KkMPUq-yiu1H0qWeKUvXKSpc',
    appId: '1:932311312417:ios:db246e42c633315f759b60',
    messagingSenderId: '932311312417',
    projectId: 'iot-fa-c7ba2',
    storageBucket: 'iot-fa-c7ba2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYMDuyrv7KkMPUq-yiu1H0qWeKUvXKSpc',
    appId: '1:932311312417:ios:db246e42c633315f759b60',
    messagingSenderId: '932311312417',
    projectId: 'iot-fa-c7ba2',
    storageBucket: 'iot-fa-c7ba2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl0HRAn9XVHC1X1b-Ppl8w2Lmo3Urxos8',
    appId: '1:932311312417:web:6b213186861c6c71759b60',
    messagingSenderId: '932311312417',
    projectId: 'iot-fa-c7ba2',
    authDomain: 'iot-fa-c7ba2.firebaseapp.com',
    storageBucket: 'iot-fa-c7ba2.firebasestorage.app',
    measurementId: 'G-X0B1BYSLQ1',
  );
}
