name: my_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  mqtt_client: ^9.8.1  # For MQTT communication with HiveMQ
  cupertino_icons: ^1.0.8
  http: ^0.13.6  # Add HTTP package for network calls
  flutter_dotenv: ^5.1.0  # Load environment variables securely
  image_picker: ^1.0.7  # Use the latest version
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Correct lint version

flutter:
  uses-material-design: true

  assets:
    - assets/profile-pic.png
    - .env  # Environment file for storing credentials
